---
apiVersion: v1
kind: ConfigMap
metadata:
  name: litmus-portal-operations-config
  namespace: ishangupta-ds
data:
  subscriberNamespace: ishangupta-ds
  workflowNamespace: ishangupta-ds
  subscriberScope: namespace
  workflowScope: namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litmusportal-frontend
  namespace: ishangupta-ds
  labels:
    component: litmusportal-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      component: litmusportal-frontend
  template:
    metadata:
      labels:
        component: litmusportal-frontend
    spec:
      containers:
        - name: litmusportal-frontend
          image: litmuschaos/litmusportal-frontend:ci
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: litmusportal-frontend-service
  namespace: ishangupta-ds
spec:
  type: NodePort
  ports:
    - name: http
      port: 9091
      targetPort: 80
  selector:
    component: litmusportal-frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmus-svc-account
  namespace: ishangupta-ds
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: namespace-admin
  namespace: ishangupta-ds
  labels:
    name: namespace-admin
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
      - workflows/finalizers
      - workflowtemplates
      - workflowtemplates/finalizers
      - cronworkflows
      - cronworkflows/finalizers
    verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: litmus-rb
  namespace: ishangupta-ds
subjects:
  - kind: ServiceAccount
    name: litmus-svc-account
    namespace: ishangupta-ds
roleRef:
  kind: Role
  name: namespace-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: litmusportal-server
  namespace: ishangupta-ds
  labels:
    component: litmusportal-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: litmusportal-server
  template:
    metadata:
      labels:
        component: litmusportal-server
    spec:
      containers:
        - name: graphql-server
          image: ishanguptads/litmusportal-server:private
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
          env:
            - name: DB_SERVER
              value: "mongo-service:27017"
            - name: JWT_SECRET
              value: "litmus-portal@123"
            - name: EXTERNAL_ADDRESS
              value: ""
            - name: SERVICE_ADDRESS
              value: "http://litmusportal-server-service:9002"
            - name: SELF_CLUSTER
              value: "true"
            - name: SUBSCRIBER_IMAGE
              value: "ishanguptads/litmusportal-subscriber:private"
            - name: SUBSCRIBER_SCOPE
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-operations-config
                  key: subscriberScope
            - name: WORKFLOW_SCOPE
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-operations-config
                  key: workflowScope
            - name: SUBSCRIBER_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-operations-config
                  key: subscriberNamespace
            - name: WORKFLOW_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-operations-config
                  key: workflowNamespace
            - name: DEPLOYER_IMAGE
              value: "ishanguptads/litmusportal-self-deployer:private"
            - name: DEPLOYER_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: litmus-portal-operations-config
                  key: subscriberNamespace
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
        - name: auth-server
          image: litmuschaos/litmusportal-auth-server:ci
          resources:
            limits:
              cpu: 200m
              memory: 250Mi
          env:
            - name: DB_SERVER
              value: "mongodb://mongo-service:27017"
            - name: JWT_SECRET
              value: "litmus-portal@123"
            - name: ADMIN_USERNAME
              value: "admin"
            - name: ADMIN_PASSWORD
              value: "litmus"
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
      serviceAccountName: litmus-svc-account
---
apiVersion: v1
kind: Service
metadata:
  name: litmusportal-server-service
  namespace: ishangupta-ds
spec:
  type: ClusterIP
  ports:
    - name: graphql-server
      port: 9002
      targetPort: 8080
    - name: auth-server
      port: 9003
      targetPort: 3000
  selector:
    component: litmusportal-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: ishangupta-ds
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      component: database
  template:
    metadata:
      labels:
        component: database
    spec:
      containers:
        - name: mongo
          image: mongo:4.2.8
          resources:
            limits:
              cpu: 200m
              memory: 400Mi
          ports:
            - containerPort: 27017
          imagePullPolicy: Always
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  namespace: ishangupta-ds
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo-service
  namespace: ishangupta-ds
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    component: database
