apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  namespace: ishangupta-ds
  name: argowf-chaos-pod-delete-1601266718
spec:
  entrypoint: argowf-chaos
  serviceAccountName: argo-chaos
  arguments:
    parameters:
      - name: adminModeNamespace
        value: ishangupta-ds
  templates:
    - name: argowf-chaos
      steps:
        - - name: initialize-engine
            template: initialize-engine
        - - name: run-chaos
            template: run-chaos
        - - name: revert-chaos
            template: revert-chaos

    - name: run-chaos
      suspend:
        duration: "40"

    - name: initialize-engine
      inputs:
        artifacts:
          - name: initialize-engine
            path: /tmp/chaosengine.yaml
            raw:
              data: |
                apiVersion: litmuschaos.io/v1alpha1
                kind: ChaosEngine
                metadata:
                  name: pod-delete-chaos
                  namespace: {{workflow.parameters.adminModeNamespace}}
                spec:
                  appinfo:
                    appns: ishangupta-ds
                    applabel: 'app=hello-world'
                    appkind: deployment
                  jobCleanUpPolicy: retain
                  monitoring: false
                  annotationCheck: 'true'
                  engineState: 'active'
                  chaosServiceAccount: litmus-namespace-admin
                  experiments:
                    - name: pod-delete
                      spec:
                        components:
                          env:
                            - name: KILL_COUNT
                              value: '1'
                            - name: TOTAL_CHAOS_DURATION
                              value: "30"
                            - name: CHAOS_INTERVAL
                              value: "10"
                            - name: FORCE
                              value: "false"
      container:
        image: lachlanevenson/k8s-kubectl
        resources:
          limits:
            memory: 128Mi
            cpu: 50m
        command: [sh, -c]
        args:
          [
            "kubectl apply -f /tmp/chaosengine.yaml -n {{workflow.parameters.adminModeNamespace}}",
          ]

    - name: revert-chaos
      container:
        image: lachlanevenson/k8s-kubectl
        resources:
          limits:
            memory: 128Mi
            cpu: 50m
        command: [sh, -c]
        args:
          [
            "kubectl delete chaosengine pod-delete-chaos -n {{workflow.parameters.adminModeNamespace}}",
          ]
